server:
  port: 8080
  http:
    coreThreads: 4
    maxThreads: 32


solon.app:
  name: 'demo-app'
  group: 'demo'

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO